name: webcosketflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client:
  http:
  web_socket_channel:
  flutter_local_notifications: ^12.0.3
  flutter_background_service: ^2.4.6
  flutter_background_service_ios: ^2.4.0
  flutter_background_service_android: ^3.0.3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
